### ISSUE TITLE
The direction of Thumbstick_Axis is opposite.

### ISSUE THREAD

**Issue by BelieveXiaoShuai** [ExtendRealityLtd/Tilia.Input.UnityInputManager#21]
### Environment

* Code source:  Tilia.Input.UnityInputManager
* Code version: 1.2.2
* Platform version: Unity 2019.2.1
* 3rd party dependencies: VRTK.Prefabs

### Steps to reproduce

When I use Teleport ray, the DirectionIndicator is always opposite from top to bottom and left to right. After my investigation, the directions of Thumbstick_HorizontalAxis and Thumbstick_VerticalAxis are opposite. The direction is only right after I change the Multiplier from 1 to -1.

### Expected behavior

When Multiplier defaults to 1, the direction is right

### Current behavior

When I use Teleport ray, the DirectionIndicator is always opposite from top to bottom and left to right. After my investigation, the directions of Thumbstick_HorizontalAxis and Thumbstick_VerticalAxis are opposite. The direction is only right after I change the Multiplier from 1 to -1.

**Comment by thestonefox** [comment]
You need to invert the Axis5 in the input manager as for some reason unity has it the opposite way round. This has been fixed in the latest version of the input manager by having the axis creator invert the axis by default. Updating to the latest version won't fix the issue though, you'll have to manually invert it if you already have it installed.
